### PR TITLE
Adding matlab repo + Matlab Script to detect Objects

### PR DESCRIPTION
**Pull request by sarimzafar**

### CODE REVIEW

**Comment by benjaminwinger** [comment]
Can one of the admins verify this patch?

**Comment by sarimzafar** [comment]
Benjamin, let me know when you merge this. I want the script to go with the repo.

**Comment by wargdogs** [comment]
Can one of the admins verify this patch?

**Comment by chrishajduk84** [comment]
I'm a little hazy on adding Matlab code to this repo... 

We won't be running Matlab code because eventually this code will be running on board the plane. (Matlab can't run on that) 

@sarimzafar @benjaminwinger  I propose we put this in a separate branch if this is really needed (one that is never merged). I understand using Matlab to test concepts,  but ultimately things should be in c++.

**Comment by chrishajduk84** [comment]
@sarimzafar anyway to convert that into c++?

**Comment by sarimzafar** [comment]
@chrishajduk84  This code is only for reference. Yes, we would not be running it but this is prototype code and incredibly useful for building and dealing with testcases.

**Pull request closed without merging**
