### PR TITLE
Added testing files to all modules

### PR DESCRIPTION
**Pull request by chrishajduk84**
The testing infrastructure is now setup for each module. Functional tests still need to be written inside these files. For instance, the JSON importer test needs to be written for the appropriate JSON file.

### CODE REVIEW

**Comment by CoatedMoose** [comment]
I don't think you should be adding files with a tilde to version control. They are supposed to be working/temp copies.

**Comment by chrishajduk84** [comment]
Tilde...oh shoot. Didn't see that.

**Comment by CoatedMoose** [comment]
Not sure what program generates those, but you should add a `*~` to your global git ignore.

**Comment by chrishajduk84** [comment]
I've added a test for target_loader, but for some reason it says:
"Undefined reference to Json::Reader:Reader() in function TargetLoader::ReadJSON(...)"
There is something wrong with the Json linker, but I'm not sure what.

My C++ is a bit sketchy...anyone?

**Pull request closed without merging**
